version: '3.8'

services:
  cline-recorder:
    build: .
    environment:
      DATABASE_URL: sqlite:///:memory:
      LOG_LEVEL: INFO
    ports:
      - "8000:8000"  # MCP server
      - "8001:8001"  # REST API
    volumes:
      - .:/app
    restart: unless-stopped
    command: ["python", "main.py", "--mode", "both"]